from pydantic import BaseModel, Field

class ExtractionSchema(BaseModel):
    reference: str = Field(default="", alias="Reference")
    alternative_reference: str = Field(default="", alias="Alternative Reference")
    address: str = Field(default="", alias="Address")
    proposal: str = Field(default="", alias="Proposal")
    application_type: str = Field(default="", alias="Application Type")
    application_received: str = Field(default="", alias="Application Received")
    application_validated: str = Field(default="", alias="Application Validated")
    application_registered: str = Field(default="", alias="Application Registered")  
    applicant_name: str = Field(default="", alias="Applicant Name")
    applicant_address: str = Field(default="", alias="Applicant Address")
    agent_name: str = Field(default="", alias="Agent Name")
    agent_address: str = Field(default="", alias="Agent Address")
    agent_phone: str = Field(default="", alias="Agent Phone")
    grid_reference: str = Field(default="", alias="Grid Reference")
    northing: str = Field(default="", alias="Northing")
    easting: str = Field(default="", alias="Easting")
    source: str = Field(default="", alias="Source")
    council_name: str = Field(default="", alias="Council Name")
    council_code: str = Field(default="", alias="Council Code")
    main_page_url: str = Field(default="", alias="Main page url")
    agent_contact_details: str = Field(default="", alias="Agent contact details")
    agent_company_name: str = Field(default="", alias="Agent Company Name")
    agent_email: str = Field(default="", alias="Agent Email")
    agent_fax: str = Field(default="", alias="Agent Fax")
    targetdec_dt: str = Field(default="", alias="Target Decision Date")
    no_of_documents: str = Field(default="", alias="No of documents")
    document_url: str = Field(default="",alias="Documents page url")
    application_status: str = Field(default="", alias="Application Status")
    actual_decision_level: str = Field(default="", alias="Actual Decision Level")
    actual_committee_date: str = Field(default="", alias="Actual Committee Date")
    advertisement_expiry_date: str = Field(default="", alias="Advertisement Expiry Date")
    agreed_expiry_date: str = Field(default="", alias="Agreed Expiry Date")
    applciation_expiry_deadline: str = Field(default="", alias="Application Expiry Deadline")
    temporary_permission_expiry_date: str = Field(default="", alias="Temporary Permission Expiry Date")